# Professional sextants

A sextant is an instrument for measuring angles between objects. They have been
used in navigation for centuries, because latitude can be inferred from a
measurement of the angle between the horizon and the noontime sun. For this
reason, professional sextants have a way of sighting the sun angle without
looking at the sun.  This method is **not** a possibility with the sextant
described below; rather the typical purpose is to infer the heights of
buildings, trees, or hills.

# A homemade sextant

A crude sextant can be created quite simply.  With it, one can find the heights
of objects, using a method invented a thousand years ago by Al Biruni (see the
References section for a blog item explaining the method).  Not only is this
fun, but it's a good way to see that high-school trigonometry is useful!

To make the sextant, follow these steps:

1. Print either the file named `sextant1.pdf` or the one named `sextant2.pdf` on
   a sheet of paper. (These files differ in how the angles are laid out. Pick
   whichever one you find easier to read.)
2. Paste it on a sheet of thick cardboard or thin wood.  (A wooden shingle
   would work well, for example.)
3. If you wish, cut along the gray outer semicircle, to eliminate corners.
4. Create a pivot at the point marked "P", either drilling a hole and inserting
   a thin dowel or stiff wire, or by driving a nail through the spot.  (If the
   latter, blunt the sharp end of the nail after you insert it.
5. Repeat step 4 at the spot marked "S".
6. Attach fishing line, dental floss, or thin string, at point "P", and attach
   something heavy at the end.  The string should be long enough to extend to
   the edge of your instrument, so that the weight doesn't rub into it.

# Using the sextant

Hold it by the pivot, and rotate the instrument so that you can sight along the
line from "P" to "S", putting something into view.  Wait a moment until the
weight stops swinging, and then press your finger on it, just past the scale.
Then, holding your finger there, read the angle on the scale.  This is the
angle between your eye and the object sighted, with respect to the horizontal.

# Example: tree height

![Diagram for measuring tree height.  $L$ is a distance paced off on the ground, $\theta$
is the angle found by sighting to the top of the tree, and $H=L\tan\theta$ is the inferred tree height.](tree.png)

As illustrated above, you can find the height $H$ of a tree on flat ground, by
pacing off a distance $L$ from it's trunk, and then finding the angle $\theta$
to the top. The height, in paces, is then given by $L\tan\theta$.  (To convert
to meters or some other unit, just take some paces on a sidewalk marking start
and end spot by scratching with chalk or a stone, and then determine your pace
length.)  If you don't have a calculator handy, you may use the table in the
Appendix to get the $\tan\theta$, and then multiply by hand to a couple of
digits.

# References

Lynch, Peter. “Al Biruni and the Size of the Earth.” ThatsMaths (blog), June
10, 2021.
https://thatsmaths.com/2021/06/10/al-biruni-and-the-size-of-the-earth/.


# Appendix: trigonometry tables

```{r echo=FALSE}
library(knitr)
angle <- seq(0, 89, 1)
sine <- sin(angle*pi/180)
cosine <- cos(angle*pi/180)
tangent <- tan(angle*pi/180)
df <- data.frame(angle,sine, cosine, tangent)
kable(df, digits=5)
```
